version: '3.3'

networks:
  react-net:
    driver: bridge

services:
  stranger:
    container_name: stranger
    #    image: php:cli-buster
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    tty: true
    volumes:
      - .:/home/app/
    networks:
      - react-net